### ISSUE TITLE
Implement connectivity to local mongodb

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#16]
We'd like our backend to have a functional connection to mongodb. We already have mongoose in place, so we'd like our express server to connect to the local mongodb instance on startup.

Lets call the mongodb datastore "challedu" and the collections "users" and "ngos"

Check this page for documentation
https://mongoosejs.com/docs/connections.html

The acceptance criteria for this pull request are:
* Express server connects to mongodb on startup
* It checks if the database and 2 schemas exist by making a test query to each one, and if not, it creates them

**Comment by student0b4dc0d3** [comment]
I am both interested and willing to take this assignment
I can take it If no one else is interested

**Comment by zannis** [comment]
Check this out for storing credentials without them being public.

https://www.npmjs.com/package/dotenv

**Comment by student0b4dc0d3** [comment]
I have partially completed this issue
The only thing pending is db and schema exist verification / creation.
I did this partial commit to overcome the bottleneck this issue has on the rest of the issues
Please verify the connectivity
TY

**Comment by student0b4dc0d3** [comment]
Completed issue requirements
Awaiting comments / apptoval
Entering Idle State
Best regards
