### ISSUE TITLE
Update user POST handler to validate and save the input to mongodb

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#17]
Lets make our POST handler smart now since we have our mongoose schemas in place.

Upon receiving a request with a json body, the user POST handler should validate the body and use the mongoose .save() method to save its input to mongodb.

Acceptance criteria:
* User POST request saves data to mongo using mongoose.
* Implement a middleware to check if the request body is a valid, reject with 400 Bad request otherwise (this logic should be inside the middleware). Implement this in a folder called 'middleware' inside the 'src' folder.
* Before saving the user to mongodb, use the bcrypt package to encode the provided password and save the encoded version. Google best practices for this or reach out to me for any clarifications. 
* Call the middleware from the POST route.

**Comment by bbouba** [comment]
Hello
Do we going to specify on the schema for each column the required key for field requirement?

**Comment by zannis** [comment]
@bbouba 
For users entity the following fields will be required:
    email
    password
    full_name
    role
    description

@bbouba Also please make sure to set the "approval_pending" field to true everytime someone makes a POST request

**Comment by bbouba** [comment]
For this requirement fields. should i use regex to control the data from user like (/.<>\';...) or i have just to control if it's empty or not?

**Comment by zannis** [comment]
Lets just check if the fields are empty for now, and I will discuss further with the guys from Challedu if they need more specific checks.

Also, after saving the user, in case of success we should return a response statusCode 201 and a body like so
{
   _id: <the newly created id>
}

If there is any error besides validation we should return a response with statusCode 500 and body 
{
    errror: <the error message>
}
