### ISSUE TITLE
Add linting to the project

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#24]
To avoid making commits that have numerous spacing/indentation/semicolons/styling conflicts, we should adopt a single coding style across the project. There are various schools of thought here and 2 main libraries that help with that, prettier and eslint.

Acceptance criteria:
* Read up on JS coding styles and suggest the coding style of your choice (maybe use one derived from a large company like twitter, netflix or airbnb)
* Add eslint (and maybe prettier) as devDependencies in the backend project
* Create an .eslintrc file at the project root folder with all the necessary linting rules
* Create a 'lint' script inside package json that calls our linter(s)
* Call the lint script before executing nodemon inside our 'check' script

**Comment by bbouba** [comment]
I would use only Eslint and prettier without airbnb...the set up is easier to manage...what do you think?

**Comment by zannis** [comment]
Sounds great from my side. Lets go with this option!

**Comment by bbouba** [comment]
I couldn't find the way to run and fix the problem in the package.json file.
But each one on the team can isert this line  "editor.codeActionsOnSave": {"source.fixAll": true } inside the seetings.json file that going to fix automaticaly the styles.
What do you think about before my first PR.?

**Comment by zannis** [comment]
Hey @bbouba I like this solution, however it's one that is dependent on the actual editor that people are using (VSCode) and I would rather not have code in the project that is dependent on software. Looking around, I found the following:

https://medium.com/@rashtay/how-to-run-eslint-using-pre-commit-hook-25984fbce17e

So this means that everytime someone commits code in this git repo, eslint will run and the committed files will have to pass linting in order for the commit to be approved. 

This one also is a helpful gist that does the same.

https://gist.github.com/broofa/730fab6ceb1686f4a1fa9977b791b1b5

This approach is only dependent on git, which we all use as part of this repository. So everyone will lint their code without having to do anything or use any specific software. Also remember to add a lint script so anyone can lint on whenever they want! Cheers
