### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by NickPapacostas** [SocialHackersClass10/ChalleduApp#25]
Available throughout frontend: 
- Log in / log out
- User properties

**Comment by ligopsychakis-michalis** [comment]
Hello team!! I want to ask.. the context api must hold all the properties that backend send us for a specific user?? Also in this ticket we only have to create the context right?

**Comment by NickPapacostas** [comment]
Hey Michalis, yes I believe you should use the API services classes @student0b4dc0d3  created (contact him Manolis for advice on using it) to get the information from the backend. And yes you should create the context ^_^ @Pauleing  hope that is good advice :)

**Comment by Pauleing** [comment]
@ligopsychakis-michalis yes you need to create the context and add the provider at the root of the app. It should be very similar to an exercice we did in class. Also for now you don't have the authentication API so you can just concsider that the login works everytime and get the info of the user (and fail if the user does not exist))
