### ISSUE TITLE
API Service class

### ISSUE THREAD

**Issue by NickPapacostas** [SocialHackersClass10/ChalleduApp#26]
Allow front end to call back end api with error handling etc. in one place

A class that allows GET, POST, PUT, DELETE calls so that we don't have `fetch` calls all over the place

**Comment by Pauleing** [comment]
The goal of this ticket is to build two abstract layers between the components and the server side API. Here are the layers : 

## Components
Needs to access the API data, calls a provider to get this data, for example : 
`await users = UserProvider.getUsers();`

## Providers : UserProvider for now, maybe later some others

High level methods like 

statis async getUsers();
static async getUser(id);
static async createUser(...);
static async deleteUser(...);

etc.
This is where you have the logic with the model (here the User object)

## APIUtils

Class that has the following methods : 
 static async get(url)
static async delete(url);
 static async post(  url, content);
static async put(url, content);

This is where you use fetch, see if the response if ok, log errors, etc.

**Comment by student0b4dc0d3** [comment]
Cheers, thank you Paulin

**Comment by student0b4dc0d3** [comment]
I have created the new branch for this ticket:
issue#26-api-service-classes

Team, before you start any changes, please make sure you are in sync and up to date by issuing following commands ( in the terminal, inside the Challedu project folder )
* git checkout master
* git pull
* git checkout ssue#26-api-service-classes

Also, kindly initiate a team meeting session, I feel we need to start implementing this issue

**Comment by student0b4dc0d3** [comment]
@Pauleing 
I am thinking the "APIUtils class" could be just a singular function encapsulating all the needed AJAX functionality.
Do you have any objections going that route?

**Comment by Pauleing** [comment]
Using only one function with the fetch is a good idea, you can call it request. But please keep the others (get, put, post, delete) and make them use this one.

**Comment by student0b4dc0d3** [comment]
So, if I understood you correctly, you want
* A module named UserProvider.js, which implements and exports a class named UserProvider, which class encapsulates the 4 basic CRUD methods for the user, and dispatches the requests through the APIUtils class ( specified below )
* A module named APIUtils.js, which implements and exports a class named APIUtils, which class encapsulates the 4 basic AJAX requests and dispatches them through a singular issueAJAXRequest function, which function will be private to the module ( is not exported ) and will handle all AJAX request dispatches and return the result
Did I successfully decode your request / intent ?

**Comment by Pauleing** [comment]
@student0b4dc0d3 Yes, this is exactly what you need to do! Can you please coordinate with the rest of the people assigned to this so you can work on it together ?

**Comment by Jallow9** [comment]
thanks, Paulin, @manolis, yesterday i did meet with aklilu we have a brief discussion and agreed on to do more research before we start. 
Please we can have a meet up at any time of your time. I was so busy yesterday and today!

**Comment by Jallow9** [comment]
Hi @Pauleing, do we have a url to call the CRUD method ?

**Comment by Pauleing** [comment]
@Jallow9  you need to run the backend from master. Talk to the backend team if needed

**Comment by student0b4dc0d3** [comment]
Good morning
@Pauleing 
Let me please rephrase @Jallow9 's question:
what URL will our outgoing AJAX requests be directed to?
In other words: All through our course we used "http://localhost:XXXX" to send our requests to. 
Now in this case, the localhost part does not apply.

**Comment by Pauleing** [comment]
@student0b4dc0d3 @Jallow9 For now use localhost, create a constant in the APIService class API_URL
