### ISSUE TITLE
Endpoint to get all NGOs

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#43]
Acceptance Criteria:

Implement GET endpoint under /ngos
Endpoint should return the following response with 200 status code: 
```
{
    ngos: [array of ngo objects]
}
```
In case of no results it should return the above response with an empty array
In case of any other error it should return 500 with 
```
{
   error: error message
}
```
The endpoint should only return the following fields:
document_state
name
image
description
affinities

**Comment by student0b4dc0d3** [comment]
implemented & committed requirements

**Comment by student0b4dc0d3** [comment]
completed additional requirements
awaiting review / comments / resolution

**Comment by student0b4dc0d3** [comment]
completed additional requirements
awaiting review
ty

**Comment by zannis** [comment]
PR accepted and merged. Closing.
