### ISSUE TITLE
Design & Implement Admin endpoints for user(s) and ngo(s)

### ISSUE THREAD

**Issue by student0b4dc0d3** [SocialHackersClass10/ChalleduApp#52]
We need a way to distinguish the resulting document(s) based on their state. We have the normal user visibility, where only "Approved" documents are returned, and we need an admin-level access, where we can return also document(s) with "Pending" and / or "Rejected" states.

This could either be implemented by additional (Admin-only-access) endpoints, or by adding "query" onto the existing URL

Any thoughts / suggestions are most welcome.
This would also affect, and be used by, the front-end.

Thank you

**Comment by student0b4dc0d3** [comment]
Good morning Team,

@zannis 
I am sorry, I may have failed to communicate my intent for this issue.
This ticket is completely irrelevant to authentication / authorization.
I am aware about the auth part of the process will get handled through middleware.

This ticket was intended with the "Pending" and "Rejected" resources
As you described in the past, admin(s) will have a "list" of pending resources for them to decide approval. To implement this list there must exist a methodology for the front-end to request said resources. This ticket/issue was meant to satisfy that back-end functionality

For your consideration

Thank you and have a great & productive day

**Comment by zannis** [comment]
**2/7 UPDATE**

Acceptance criteria
Backend side:
Add support for query parameter: document_state on GET users and GET ngos endpoints (this shouldn't affect the filtering functionality about the roles (admin vs simple users))
Frontend side:
Create methods on the UserProvider and NGOProvider to getActive getPending and getRejected Users and NGOs respectively, using the above implementation.

**Comment by zannis** [comment]
UPDATE 13/7
Also replace the document_state in the user schema, to be a string instead of an array.

**Comment by student0b4dc0d3** [comment]
I has come to my attention that the requirements of this ticket are in conflict with those of ticket #66

We may have to talk about this in more detail, since this ticket's requirements seem to supersede  those of the other ticket

Thank you

**Comment by GMouzakis** [comment]
we have complete the ticket with the PR #118.
