### ISSUE TITLE
APIUtils.js lines 27 28 29 33 change the res to result

### ISSUE THREAD

**Issue by Manolispro** [SocialHackersClass10/ChalleduApp#55]
APIUtils.js lines 27 28 29 33 change the res to result

_Originally posted by @Manolispro in https://github.com/SocialHackersClass10/ChalleduApp/pull/37#issuecomment-649779170_

**Comment by student0b4dc0d3** [comment]
This is handled by issue #56  and possible solved by PR #57 

Sorry for the duplication, when I picked up the subject there was no ticket
( https://github.com/SocialHackersClass10/ChalleduApp/projects/1 )
so I created one and went from there.

This issue can be deleted or merged with issue #56 

Thank you

**Comment by zannis** [comment]
Closing this one since it's handled by #56 .
