### ISSUE TITLE
Design wireframes for the basic screens

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#6]
Use a wireframing tool of your choice to design wireframes for the following screens:

> Registration screen
> Login screen
> Dashboard (what logged in users see) 
> User profile list
> NGO profile list
> User profile creation form
> NGO profile creation form
> Pending approvals screen

**Comment by Pauleing** [comment]
We’re gonna use bootstrap so maybe have this in mind when working on the designs.

The team is meeting altogether tomorrow to finalize the wireframing / designs

**Comment by Pauleing** [comment]
https://www.figma.com/file/dDMQhO9ueifm913iWQ0MpQ/Untitled?node-id=0%3A1
