### ISSUE TITLE
Implement an ending for uploading images and documents for NGOs

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#68]
We need an endpoint where a user will be able to upload images for their NGO.

Acceptance criteria
Create a POST endpoint under
/ngos/:id/upload
Endpoint should be accessible only by the role user-ngo
The endpoint should also check that the ngo id in the params has the requesting user as it's representative . This should happen inside the endpoint, not in a middleware. If not, it should return 403 with
```
{
error: You are unauthorized to upload documents for this NGO
}
```
The endpoint should accept bodies with content type "multipart/form-data" (take a look in the formidable library for further info)
It should receive a file via the body, it should validate that it's filetype is image or PDF docenr and if so it should save it under the NGO's document in mongodb using gridfs.
If the file is saved successfully, it should return 201, and if there is another error, it should return 400 with

```
{
   error: Error during image/document upload.
}
```
Every validation should fail and return an error 400 with the appropriate message.

**Comment by bbouba** [comment]
do we have to test if content-type is equal to multipart/form-data...or how to handle that?
