### ISSUE TITLE
Technical architecture Frontend - Finish initial setup

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#7]
Choose the graphic framework
Which library to use for state and data storage
Make these choices and add the dependencies in package.json

**Comment by Pauleing** [comment]
Technical choices : 
- bootstrap of the graphic framework 
- context API to keep the state of the user (+log in and log off)

TODO to finish this ticket : 
After looking at what the other team has done concerning the designs, prepare the list of the things that you're gonna need in bootstrap / bootstrap-react, and post it here

**Comment by yuskara** [comment]
=========================== 1
WelcomeScreen
-------------
img=logo
form 
input login
input register
/form

======================== 2

RegistrationScreen
------------------
img=logo
form
input email
input password
input password
select NGO
/form

========================= 3

RegistrationApprovalUserN
------------------
 Message Box

========================= 4

DashboardAdmin
------------------
<Navbar/>
<Menu/>
img=logo
Table
button

========================= 5

Navbar
------------------
links
#home
#users
#NGO
#admin

========================= 6

DashboardMenu
------------------
Manage user
NGO Profiles
Mentor Profile

========================= 7

LoginScreen
------------------
img=logo
form
input email
input password
button login
/form

========================= 8

NgoProfileForm
------------------
<Navbar/>
img=logo
form
input name
input description
button uploadPicture
button uploadDocument
button submit
/form

========================= 9

UserProfileForm
------------------
<Navbar/>
img=logo
form
input fullName
input description
input email
input address
input phone
button uploadPicture
button submit
/form

========================= 10

UserProfileList
------------------
<Navbar/>
img=logo
<CardList/>
========================= 11

CardList
------------------
picture
name
type
description

========================= 12

CardUserUpdate
------------------
picture
name
mail
phone
web
loc

========================= 13

UserProfileUpdate
------------------
<Navbar/>
img=logo
<CardUserUpdate/>

text description
button edit

========================= 14

NgoProfileUpdate
------------------
<Navbar/>
img=logo
<CardUserUpdate/>

text description
document
button edit

**Comment by yuskara** [comment]
Pseudo code about components

**Comment by NickPapacostas** [comment]
Deliverables:
In `frontend` folder:

- React project
   - create-react-app

- Bootstrap-react installed
