### ISSUE TITLE
Link login page with backend API (and context)

### ISSUE THREAD

**Issue by Pauleing** [SocialHackersClass10/ChalleduApp#71]

**Comment by ligopsychakis-michalis** [comment]
Hello team!! So our goal for this ticket is to transform the login post request in a way to decode the the access key, take the user's id and finally make a get request to users/:id  endpoint and take the actual user's info???

**Comment by Pauleing** [comment]
Yes, also store the authentication info and user info in the context , then use the access key in all UserProvider / APIService requests

**Comment by ligopsychakis-michalis** [comment]
ok thanks Paulin!!

**Comment by student0b4dc0d3** [comment]
After this issue's PR request has already been merged, there are following "Problems" :

* UserProbider is still missing a "loginUser" method
* Only 1 of the exposed methods ( getUser ) makes use of any token(s) ( only the access token )
* The refresh token is used nowhere

I had in mind that all the methods would include in their AJAX request header both token, so the back-end can verify the access token validity or, in case it has expired, use the refresh token to refresh the access token

**Comment by ligopsychakis-michalis** [comment]
hi manoli.. I think in a way you are right... 

as I understand when access token expired, frontend makes a new request to another route with the refresh token passed to headers and the backend from this route generates again the tokens so to refresh the expiration day..

So maybe this issue can be a new ticket where in the Form.js, if frontend gets error for expired access token, will make a new request for refresh....
