### ISSUE TITLE
Authorization - Token Refresh process

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#78]
Acceptance criteria
Create a new POST endpoint under /auth/refresh
This endpoint should receive the following body
```
{
    refresh_token: <token>
}
```
Use our jwt library to validate it using the refresh_token_key and make sure it is not expired.
Do not use the jwt middleware since this request will not include an authorization header, or make sure we ignore it even if it does (since the access_token is going to be expired or invalid anyway)
If so, it should create a new fresh pair of access_token and refresh_token and return them to the user. Exactly in the same format as the login endpoint.
Otherwise, it should return 401 with
```
{
    error: 'Refresh token expired. Please login with your credentials.'
}
```

**Comment by ligopsychakis-michalis** [comment]
Hello team... I don't understand, if refresh token is expired then what's happening??? I mean the access token has the refresh token to update it, but the refresh token what it has to update it??
