### ISSUE TITLE
Discrepancy between front & back end : create & update user methodology

### ISSUE THREAD

**Issue by student0b4dc0d3** [SocialHackersClass10/ChalleduApp#81]
It has come to my attention that the "update user" endpoint on the back-end is a restricted resource, accessible only to admin roles.

Also it has come to my attention that during user registration by the front-end the "create user" AJAX call will only supply following user info:
*   email
*   password
*   role

When I asked for "when" the rest of the user specific info will be provided, I received the following answer :
"at a later point, by the user, after login, through their account info"

So... we have conflicting design/conditions.

We need to either
*   enable access to the back-end's "update user" endpoint regardless of role
or
*   enable the front-end to collect + submit all user related info at "registration" time

For your consideration.
Thank you

**Comment by zannis** [comment]
Nice find @student0b4dc0d3 !
My suggestion is the following: alter the update user endpoint on the backend to be accessible by all users, BUT make the document_state field editable only by the admin. In terms of implementation we could handle this simply, by checking for the role and conditionally deleting the document_state from the incoming body before making the change. I am open to alternatives however and moving  this to the todo list.

**Comment by student0b4dc0d3** [comment]
No arguments for the above suggestion, but we need the JWT PR resolved in order to further any more changes to routes, b/c said PR does change all the existing routes
Thank you

**Comment by student0b4dc0d3** [comment]
I think of conditionally removing both "role" and "document_state" from the incoming user data unless access request originated from an admin-typed role.

Would that satisfy the requirements and still cover the needed changes or is there anything I have overlooked?

Thank you for your input

**Comment by zannis** [comment]
@student0b4dc0d3 
You raised a valid point, you can use a mongoose 'pre' middleware to do this:
So before updating (or during pre-update) you can make a check that the specified fields are NOT modified, and if so invalidate the incoming query. See below:
https://stackoverflow.com/questions/26342081/mongoose-disallow-updating-of-specific-fields

**Comment by student0b4dc0d3** [comment]
There is more than we anticipated, that needs dealt with here.

For example, at some point the user registration has "dropped" the role field, at first we had thought that this role would be defined on registration and never change but now the front-end registration only offers email and password.
That change leads to offer update to role even when the request is not initiated by an admin.

I feel like we may have to talk about this issue in more detail

**Comment by zannis** [comment]
> For example, at some point the user registration has "dropped" the role field, at first we had thought that this role would be defined on registration and never change but now the front-end registration only offers email and password.
> That change leads to offer update to role even when the request is not initiated by an admin.

@student0b4dc0d3 @Pauleing 
This sounds like a defect of the current implementation. It was clear in the requirements that registration should include email password and role. So from my side, the fix should be to bring back the role on the Registration page.

**Comment by zannis** [comment]
I think this has been addressed in other tickets so it's safe to close it. @student0b4dc0d3 correct?

**Comment by student0b4dc0d3** [comment]
completed requirements and issued PR #127 
please review and comment / resolve
thank you
