### ISSUE TITLE
Add NGOProvider

### ISSUE THREAD

**Issue by Pauleing** [SocialHackersClass10/ChalleduApp#93]

**Comment by student0b4dc0d3** [comment]
completed implementation of requirements of ticket #93
please kindly review and comment / resolve
thank you

**Comment by Manolispro** [comment]
when i try to console.log the data.ngos from NGOProvider.getNGOs i m getting nogs with approval_pending and empty array of document maybe should be document_state : Approved ?

**Comment by Pauleing** [comment]
@Manolispro you should ask on the front end channel

**Comment by Manolispro** [comment]
i dont think that front end has something to do with document_state and routes but i dont know maybe the issue was the unfinished ticket  #52 so i ll try again
